--- 
title: "Title Placeholder"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load in Specific Packages
```{r}
library(readr)
library(tidyr)
library(dplyr)
library(here)
library(lemon)
library(kableExtra)
library(ggplot2)
library(reshape())
library(hexbin)
library(data.table)
library(GGally)
library(formattable)
library(viridis)
```

### Load in the data 
```{r}
cancerReg <- read.csv("C:\\Users\\romin\\ToyRepo\\Models\\cancerReg.csv") 
```


### Remove Uncessary Data for Analysis
```{r}
cancerReg <- cancerReg %>% select(-period,-area_type,-type_definition,-indicator, -upper_confidence_interval, -lower_confidence_interval, -numerator)
cancerReg
```

```{r}

```

### Display Summary of All Data
```{r}

# ggplot(cancerReg,aes(x=year, y= measure, col=area_name)) + geom_line() + geom_point()
# ggplot(cancerReg, aes(x=area_name, y=measure, fill=area_name)) + geom_violin()
# ggparcoord(data= cancerReg, columns = c(), groupColumn = "area_name")
# ggplot(cancerReg, aes(fill=year, y=measure, x=area_name)) + geom_bar(position = "stack", stat = "identity")
ggplot(cancerReg, aes(x = year, y = measure, fill = area_name)) +  geom_area(alpha=0.6 , size=.5, colour="white") +
    scale_fill_viridis(discrete = T) 
``` 

### Summary Table of Data Within Graph 
```{r}
customGreen0 = "#DeF7E9"

customGreen = "#71CA97"

customRed = "#ff7f7f"
# colnames(healthBoardData)
# healthBoardData <- healthBoardData %>%
#     mutate(
#         Average = round(rowMeans(select(., starts_with("measure.")), na.rm = TRUE), 2),

#     )
### This one works for creating some weird random diff
# healthBoardData <- reshape(cancerReg, idvar = "area_name", timevar = "year", v.names = "measure", direction = "wide")

# healthBoardData <- cancerReg %>%
#     arrange(area_name, year) %>%
#     group_by(area_name) %>%
#     mutate(measure_diff = c(NA, diff(measure)))
# healthBoardData


healthBoardData <- cancerReg %>% pivot_wider(names_from = year, values_from = measure)
healthBoardData <- healthBoardData %>%
    mutate(
        Average = rowMeans(select(., `2003`:`2020`), na.rm = TRUE),
        Difference = across(`2003`:`2020`, ~ . - lag(.))
    )
head(healthBoardData)
``` 